name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker_create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Step 3 - Build and push Docker image
        run: |
           
           TAG=${GITHUB_REF#refs/tags/}
           docker build -t mkha1/smm_backend:$TAG .
           docker tag mkha1/smm_backend:$TAG mkha1/smm_backend:latest
           docker push mkha1/smm_backend:$TAG
           docker push mkha1/smm_backend:latest

      - name: Step 4 - Trigger Render deploy hook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X GET "$RENDER_DEPLOY_HOOK_URL"


      

